server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA
    location / {
        try_files $uri /index.html;
    }

    # Cache pesado (performance)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # gzip (melhora MUITO)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
